ALTER TABLE "videos" ADD COLUMN "mux_status" text;-
ALTER TABLE "videos" ADD COLUMN "mux_asset_id" text;
ALTER TABLE "videos" ADD COLUMN "mux_upload_id" text;
ALTER TABLE "videos" ADD COLUMN "mux_playback_id" text;
ALTER TABLE "videos" ADD COLUMN "mux_track_id" text;
ALTER TABLE "videos" ADD COLUMN "mux_track_status" text;
ALTER TABLE "videos" ADD CONSTRAINT "videos_mux_asset_id_unique" UNIQUE("mux_asset_id");
ALTER TABLE "videos" ADD CONSTRAINT "videos_mux_upload_id_unique" UNIQUE("mux_upload_id");
ALTER TABLE "videos" ADD CONSTRAINT "videos_mux_playback_id_unique" UNIQUE("mux_playback_id");
ALTER TABLE "videos" ADD CONSTRAINT "videos_mux_track_id_unique" UNIQUE("mux_track_id");