import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import "./globals.css";
import { ReactNode } from "react";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: "New Tube Clone",
  description: "Generated by create next app",
};
const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
};
export default RootLayout;